apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "suricata.fullname" . }}-rules
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "suricata.labels" . | nindent 4 }}
    component: rules
data:
  suricata.rules: |
    {{- .Values.rules | nindent 4 }}
